"""Orders migration

Revision ID: 36d4b382a408
Revises: 2a139b49c1a2
Create Date: 2023-03-02 15:30:21.807902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36d4b382a408'
down_revision = '2a139b49c1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('total_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', mysql.DECIMAL(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###
