"""Orders migration

Revision ID: a2135efec449
Revises: 3dc5dc5ccd2a
Create Date: 2023-02-26 19:52:44.704992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2135efec449'
down_revision = '3dc5dc5ccd2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(),
               existing_nullable=False)
        batch_op.alter_column('total_cost',
               existing_type=mysql.FLOAT(),
               type_=sa.DECIMAL(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('total_cost',
               existing_type=sa.DECIMAL(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('cost',
               existing_type=sa.DECIMAL(),
               type_=mysql.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
