language: python

python:
  - 3.9
install:
  - pip install -r requirements.txt

script:
  - pylint event_wave_app
  - coverage run -m unittest discover event_wave_app/tests
  - coverage report

after_success:
  - coveralls